Aplikacija/Levres/Controllers/HomeController.cs
 using Levres.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Levres.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        [Authorize(Roles="Administrator,Zaposlenik")]
        public async Task<IActionResult> ProcjenaVrijednostiView()
        {
            return View();
        }

        [HttpPost]
        [Authorize(Roles = "Administrator,Zaposlenik")]
        public async Task<IActionResult> ProcjenaVrijednostiView([Bind("kilometraza,stete,brojVlasnika,model,godinaProizvodnje,cijena")] PolovniAutomobil car)
        {
            double approximatedPrice = Calculate(car);
            ViewBag.ApproximatedPrice = approximatedPrice;
            return View(car);
        }

        public double Calculate(PolovniAutomobil car)
        {
            if (car == null)
            {
                throw new ArgumentNullException(nameof(car));
            }
            double basePrice=0;
            if (car.model == Model.Tokan) basePrice = 30000;
            else if (car.model == Model.Belovan) basePrice = 25000;
            else if (car.model == Model.XC60) basePrice = 45000;
            else if (car.model == Model.DY6) basePrice = 40000;
            else if (car.model == Model.TOK12) basePrice = 50000;

            if (car.kilometraza > 150000)
                basePrice -= basePrice * 0.2;
            else if (car.kilometraza > 100000)
                basePrice -= basePrice * 0.1;
            else if (car.kilometraza > 50000)
                basePrice -= basePrice * 0.05;

            if (!string.IsNullOrEmpty(car.stete))
                basePrice -= basePrice * 0.1;

            if (car.brojVlasnika > 1)
                basePrice -= basePrice * 0.05 * (car.brojVlasnika - 1);

            basePrice = basePrice * Math.Pow((1 - 0.05), (DateTime.Now.Year-car.godinaProizvodnje.Year));

            return Math.Round(basePrice,2);
        }
    }
}

Aplikacija/Levres/Controllers/OpremaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Levres.Data;
using Levres.Models;
using Microsoft.AspNetCore.Authorization;

namespace Levres.Controllers
{
    public class OpremaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public OpremaController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Oprema
        [Authorize(Roles="Administrator")]
        public async Task<IActionResult> Index()
        {
            return View(await _context.Oprema.ToListAsync());
        }

        [Authorize(Roles = "Administrator,Zaposlenik")]
        public async Task<IActionResult> PregledOpremeView(Model? model, string? pretraga)
        {
            var opremaList = _context.Oprema.AsQueryable();

            if (model!=null)
            {
                opremaList = opremaList.Where(o => o.model == model);
            }

            if (!string.IsNullOrEmpty(pretraga))
            {
                opremaList = opremaList.Where(o => o.nazivDijela.Contains(pretraga));
            }
            ViewData["Model"] = model;
            ViewData["Pretraga"] = pretraga;

            return View(opremaList.ToList());
        }

        // GET: Oprema/Details/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oprema = await _context.Oprema
                .FirstOrDefaultAsync(m => m.id == id);
            if (oprema == null)
            {
                return NotFound();
            }

            return View(oprema);
        }

        // GET: Oprema/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Oprema/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Create([Bind("id,nazivDijela,model,kolicina,cijena")] Oprema oprema)
        {
            if (ModelState.IsValid)
            {
                oprema.id = Guid.NewGuid();
                _context.Add(oprema);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(oprema);
        }

        // GET: Oprema/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oprema = await _context.Oprema.FindAsync(id);
            if (oprema == null)
            {
                return NotFound();
            }
            return View(oprema);
        }

        // POST: Oprema/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(Guid id, [Bind("id,nazivDijela,model,kolicina,cijena")] Oprema oprema)
        {
            if (id != oprema.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(oprema);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OpremaExists(oprema.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(oprema);
        }

        // GET: Oprema/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var oprema = await _context.Oprema
                .FirstOrDefaultAsync(m => m.id == id);
            if (oprema == null)
            {
                return NotFound();
            }

            return View(oprema);
        }

        // POST: Oprema/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var oprema = await _context.Oprema.FindAsync(id);
            if (oprema != null)
            {
                _context.Oprema.Remove(oprema);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OpremaExists(Guid id)
        {
            return _context.Oprema.Any(e => e.id == id);
        }
    }
}

Aplikacija/Levres/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Levres";
}

@if (!User.IsInRole("Administrator") && !User.IsInRole("Zaposlenik"))
{
    <div id="carouselExampleControls" class="carousel slide h-25" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/images/carousel/1.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/images/carousel/2.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/images/carousel/3.png" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="container justify-content-center align-items-center text-center pt-4">
        <h1 class="archivo-h1 w-100 text-center">levres</h1>
        <h3 class="archivo-light w-100 justify-content-center">novi način kupovine vašeg novog vozila</h3>
        <p class="w-100 justify-content-center mt-3">
            Dobrodošli na Levres – Vaš pouzdan partner za kupovinu novih i polovnih vozila!

            U Levresu smo posvećeni pružanju jedinstvenog iskustva u kupovini vozila koje se prilagođava vašim potrebama i željama. Naša misija je da revolucioniramo tržište automobila kroz inovativan pristup prodaji, omogućavajući vam jednostavan i transparentan proces odabira i kupovine vašeg novog ili polovnog automobila.
        </p>
    </div>
}
else if (User.IsInRole("Kupac"))
{
    <div id="carouselExampleControls" class="carousel slide h-25" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="~/images/carousel/1.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/images/carousel/2.png" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="~/images/carousel/3.png" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleControls" data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
    <div class="container justify-content-center align-items-center text-center pt-4">
        <h1 class="archivo-h1 w-100 text-center">levres</h1>
        <h3 class="archivo-light w-100 justify-content-center">novi način kupovine vašeg novog vozila</h3>
        <p class="w-100 justify-content-center mt-3">
            Dobrodošli na Levres – Vaš pouzdan partner za kupovinu novih i polovnih vozila!

            U Levresu smo posvećeni pružanju jedinstvenog iskustva u kupovini vozila koje se prilagođava vašim potrebama i željama. Naša misija je da revolucioniramo tržište automobila kroz inovativan pristup prodaji, omogućavajući vam jednostavan i transparentan proces odabira i kupovine vašeg novog ili polovnog automobila.
        </p>
    </div>
}
else if (User.IsInRole("Zaposlenik"))
{
    <div class="w-100 text-center m-auto">
        <h1 class="archivo-h1 mt-2">Dobrodošao</h1>
    </div>
    <div class ="col-md-10 m-auto mt-5">
        <div class="row">
            <div class="col-md-4">
                <a class="car-card-a">
                    <div class="car-card">
                        <div class="car-image-cont">
                            <img src="~/images/Procjena.jpg">
                        </div>
                        <div class="car-card-body">
                            <h4 class="archivo-medium">PROCJENA VRIJEDNOSTI VOZILA</h4>
                            <div class="w-100 d-flex justify-content-center mt-3">
                                <a asp-area="" asp-controller="Home" asp-action="ProcjenaVrijednostiView" class="btn btn-dark">Otvori</a>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a class="car-card-a">
                    <div class="car-card">
                        <div class="car-image-cont">
                            <img src="~/images/Servis.jpg">
                        </div>
                        <div class="car-card-body">
                            <h4 class="archivo-medium">PREGLEDAJ ZAKAZANE SERVISE</h4>
                            <div class="w-100 d-flex justify-content-center mt-3">
                                <a asp-area="" asp-controller="Servis" asp-action="Index" class="btn btn-dark">Otvori</a>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
            <div class="col-md-4">
                <a class="car-card-a">
                    <div class="car-card">
                        <div class="car-image-cont">
                            <img src="~/images/Oprema.jpg">
                        </div>
                        <div class="car-card-body">
                            <h4 class="archivo-medium">PRONAĐI ZAMJENSKI DIO ZA VOZILO</h4>
                            <div class="w-100 d-flex justify-content-center mt-3">
                                <a asp-area="" asp-controller="Oprema" asp-action="PregledOpremeView" class="btn btn-dark">Otvori</a>
                            </div>
                        </div>
                    </div>
                </a>
            </div>
        </div>
      </div>
}
else if (User.IsInRole("Administrator"))
{
    <h1 class="archivo-h1 w-100 text-center">Administratorski pregled</h1>
    <div class="col-md-10 m-auto mt-5">
        <div class="row">
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Automobil" asp-action="Index" class="btn btn-dark">Pregled Automobila</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="NoviAutomobil" asp-action="Create" class="btn btn-dark">Kreiraj Novi Automobil</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="PolovniAutomobil" asp-action="Create" class="btn btn-dark">Kreiraj Polovni Automobil</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Home" asp-action="ProcjenaVrijednostiVIew" class="btn btn-dark">Procjena Vrijednosti</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Konfiguracija" asp-action="Index" class="btn btn-dark">Pregled Konfiguracija</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Narudzba" asp-action="Index" class="btn btn-dark">Pregled Narudžbi</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Oprema" asp-action="Index" class="btn btn-dark">Pregled Opreme</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Oprema" asp-action="PregledOpremeView" class="btn btn-dark">Oprema</a>
            </div>
            <div class="col-md-4 mt-4">
                <a asp-area="" asp-controller="Servis" asp-action="Index" class="btn btn-dark">Pregled Servisa</a>
            </div>
        </div>
    </div>
}
<style>
    .filter-container {
        border: 2px solid #ddd;
        background-color: ghostwhite;
        box-shadow: 0px 4px 7px 0px rgba(0,0,0,0.57);
        border-radius: 15px;
        padding: 20px;
    }

    .car-card-a {
        text-decoration: none;
        color: inherit;
    }

    .car-card {
        text-decoration: none;
        color: inherit;
        box-shadow: 0px 4px 7px 0px rgba(0,0,0,0.57);
        border: 1px solid #ddd;
        background-color: ghostwhite;
        border-radius: 15px;
        overflow: hidden;
        margin-bottom: 20px;
    }

    .car-image-cont {
        width: 100%;
        display: flex;
        height: 15em;
        background-color: #cacaca;
        overflow: hidden;
        align-items: center;
        justify-content: center;
    }

        .car-image-cont img {
            height: 100%;
            margin: 0 auto;
        }

    .car-card-body {
        text-decoration: none;
        color: inherit;
        padding: .5em;
    }

    .car-card-a:hover {
        color: gray;
    }

    .car-card-body p {
        text-decoration: none;
        color: inherit;
    }

    .car-card-body h5 {
        text-decoration: none;
        color: inherit;
    }

    .car-card-body h4 {
        text-decoration: none;
        color: inherit;
    }
</style>

Aplikacija/Levres/Views/Home/ProcjenaVrijednostiView.cshtml
@model Levres.Models.PolovniAutomobil

@{
    ViewData["Title"] = "Procjena";
}
<div class="w-100 text-center m-auto">
    <h1 class="archivo-h1 mt-2 fw-bold">Procjena vrijednosti vozila</h1>
</div>
<div class="detail-cont mt-3 w-75 m-auto">
    <div class="row">
        <div class="col-md-6 p-3">
    <form asp-action="ProcjenaVrijednostiView" method="post">
        <div class="form-group">
            <label for="Model">Model:</label>
            @Html.DropDownListFor(model => model.model, new SelectList(Enum.GetValues(typeof(Levres.Models.Model))), "Izaberi", htmlAttributes: new { @class = "form-control" })
        </div>
        <div class="form-group">
            <label for="GodinaProizvodnje">Godina proizvodnje:</label>
            <input type="month" class="form-control" id="GodinaProizvodnje" asp-for="godinaProizvodnje" />
        </div>
        <div class="form-group">
            <label for="Kilometraza">Kilometraža:</label>
            <input type="number" class="form-control" id="Kilometraza" asp-for="kilometraza" />
        </div>
        <div class="form-group">
            <label for="Stete">Štete:</label>
            <input type="text" class="form-control" id="Stete" placeholder="Ostaviti prazno ako nema" asp-for="stete" />
        </div>
        <div class="form-group">
            <label for="BrojVlasnika">Broj vlasnika:</label>
            <input type="number" class="form-control" id="BrojVlasnika" asp-for="brojVlasnika" />
        </div>
        <button type="submit" class="btn btn-dark px-3 py-2 m-auto mt-3">Procijeni</button>
    </form>
        </div>    
        <div class="col-md-6 d-flex row text-center align-items-center">
            <div class="col-sm-12">
                <h4 class="">Procjena vrijednosti: </h4>
            @if (ViewBag.ApproximatedPrice != null){
                <h2 class="fs-1">@ViewBag.ApproximatedPrice KM</h2>
            }
            </div>
        </div>
    </div>
</div>